spring:
  application:
    name: eureka_server

server:
  port: 8000

#It is server (service registry)
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka


